### ISSUE TITLE
Inappropriate collisions with lance cores

### ISSUE THREAD

**Issue by yusufmte** [yusufmte/joustronauts#4]
Sometimes lance cores detect inappropriate collisions (eg through the "handguard"), seemingly particularly at higher velocities. Thickening the handguard might help?

**Comment by ebrahimebrahim** [comment]
Another possible solution is to add another layer of validation: when a collision is detected, do some kind of explicit geometry calculation to ensure that it's a valid collision. The calculation can depend on the specifics of the lance shape. For example maybe lances are shaped such that a valid collision can only occur when the direction vectors of the lances are at an acute angle to each other (idk you'd have to think about whether this is correct). This can be checked by seeing if the dot product of the direction vectors is positive.

**Comment by yusufmte** [comment]
Ty for the idea! I was thinking about this. I think one problem with that specific condition is that I want collisions between the core of one lance and the BACK of another also to count. One possible solution would be to separate the shaft and back of the lance into separate components and use opposite angles for these two, but that starts to feel a bit clunky.

It seems the actual source of this issue stems from the Godot physics engine itself. When objects are moving too fast prior to a collision, they can "tunnel" into each other and go through something they're supposed to bounce off of. A feature called continuous collision detection is supposed to check for collisions frame-by-frame to prevent this, but isn't currently functional which is an open issue (https://github.com/godotengine/godot/issues/9071).

A [peurhaps slightly peupy] workaround that seems to have worked (https://github.com/yusufmte/joustronauts/commit/55b9e5a053022b7b293ca49fa49bd5ee537c4a42) is increasing the physics FPS to prevent this tunneling. After doing this, I haven't been able to replicate the inappropriate core collision bug.
